apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: openwebui
  namespace: vllm-semantic-router-system

# Resources that make up the OpenWebUI deployment
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: openwebui
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: semantic-router

# Namespace for all resources
namespace: vllm-semantic-router-system
